// Socket Events - Shared between client and server
const CLIENT_EVENTS = {
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  START_GAME: 'START_GAME',
  SEND_CLUE: 'SEND_CLUE',
  SELECT_WORD: 'SELECT_WORD',
  END_TURN: 'END_TURN',
  UPDATE_PLAYER: 'UPDATE_PLAYER'
};

const SERVER_EVENTS = {
  ROOM_UPDATE: 'ROOM_UPDATE',
  GAME_UPDATE: 'GAME_UPDATE',
  ERROR: 'ERROR',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  GAME_STARTED: 'GAME_STARTED',
  CLUE_RECEIVED: 'CLUE_RECEIVED',
  WORD_SELECTED: 'WORD_SELECTED',
  TURN_ENDED: 'TURN_ENDED',
  GAME_ENDED: 'GAME_ENDED'
};

module.exports = {
  CLIENT_EVENTS,
  SERVER_EVENTS
};
